### ISSUE TITLE
Melhoramento de instancia de classe em classes DAO.

### ISSUE THREAD

**Issue by andremartinsds** [RickSantiago/Inbook_projeto#1]
O ideal seria ter apenas uma conexão no sistema inteiro e sempre ficar recuperando a mesma, você poderá fazer o seguinte em suas classes DAO:

```
<?php
class CategoriaDao
{
 private static $conexao;
     public function __construct() {
         self::$conexao = new PDOUtil();
}
     public function InserirCategoria(Categoria $categoria) 
        {
            $insert = self::$conexao->getStance()->prepare("INSERT INTO categoria(nome_categoria) VALUES(:nome_categoria)");
            $insert->bindValue(":nome_categoria", $categoria->getNomeCategoria());          
            $insert->execute();
        }
}
```

O que acha?

**Comment by RickSantiago** [comment]
Recebi seu comentario, do qual voce tinha falo ontem, não tinha visto pq foi pro meu hotmail... mas acho interessante vou fazer as modificações, Muito Obrigado

Date: Tue, 28 Apr 2015 19:14:07 -0700

**Comment by andremartinsds** [comment]
massa ;)

Em ter, 12 de mai de 2015 às 10:28, Ricardo Santiago Morais <
notifications@github.com> escreveu:

**Comment by andremartinsds** [comment]
issue finalizada
